/*@@ Generated by Wedit @@ */
#include <windows.h>
#include <lfc.h>
#include "txtbookerres.h"

/*@@Callbacks Section--------------------------------------Callbacks Section@@*/
/*@@Dialog "Dlg100"------------------------------------------Dialog "Dlg100"@@*/
static ST_DIALOGBOX *Set_Dlg100_Fields(HWND hwnd)
{
	struct _Dlg100 *s;
	ST_DIALOGBOX *std = GetSTControlFromHwnd(hwnd);
	s = malloc(sizeof(struct _Dlg100));
	s->idcontent = GetControl(std,108);
	s->idurl = GetControl(std,107);
	s->idgrab = GetControl(std,106);
	s->idparse = GetControl(std,104);
	s->ctrl101 = GetControl(std,101);
	s->idcbpend = GetControl(std,103);
	s->idlblpstart = GetControl(std,112);
	s->idcbpstart = GetControl(std,102);
	s->hwnd = hwnd;
	std->Data->pDlgStruct = s;
	return std;
}

BOOL APIENTRY Dlg100(HWND hwnd,UINT msg,WPARAM wParam,LPARAM lParam)
{
	ST_DIALOGBOX *std;
	struct _Dlg100 *s;
	
	std = GetSTControlFromHwnd(hwnd);
	if (std && std->Data)
	{
		s = std->Data->pDlgStruct;
		if (s)
		{
			s->wParam = wParam;
			s->lParam = lParam;
		}
	}
	switch(msg)
	{
		case WM_INITDIALOG:
			/* Initialization of the dialog box */
			std = ST_InitDialogBox(hwnd);
			Set_Dlg100_Fields(hwnd);
			if (!(std && std->Data)) break;
			s = std->Data->pDlgStruct;
			if (!s) break;
			Dlg100Init(std,s);
			break;
		case WM_COMMAND:
			switch (LOWORD(wParam))
			{
				case IDCONTENT:
				break;
				case IDURL:
				break;
				case IDGRAB:
					Dlg100GrabSelected(GetControl(std,106),s);
				break;
				case IDPARSE:
					Dlg100ParseSelected(GetControl(std,104),s);
				break;
			}
			break;
		case WM_DESTROY:
			/* Remove the input arguments property */
			RemoveProp(hwnd,"InputArgument");
			break;
		case WM_NCDESTROY:
			ST_DestroyDialogBox(hwnd);
			break;
	}
	return(HandleDefaultMessages(hwnd,msg,wParam,lParam));
}
int RunDlg100(HWND parent)
{
	return DialogBox((HANDLE)GetWindowLong(parent,GWL_HINSTANCE),MAKEINTRESOURCE(100),parent,Dlg100);
}
HWND StartDlg100(HWND parent)
{
	return CreateDialog((HANDLE)GetWindowLong(parent,GWL_HINSTANCE),MAKEINTRESOURCE(100),parent,Dlg100);
}
