/*@@ Generated by Wedit @@ */
#include <windows.h>
#include <lfc.h>
#include <netutils.h>
#include <gc.h>

#include "txtbookerres.h"
#include "msgprintf.h"
#include "regex_helper.h"
#include "encodecvt.h"

#define MAX_STRLEN 256

typedef struct page_info {
	char title[MAX_STRLEN];
	char url[MAX_STRLEN];
} page_info_t;

typedef struct book_info {
	char url[MAX_STRLEN];
	int pages;
	page_info_t pi[1024*5];
} book_info_t;

book_info_t bi;
book_info_t *g_pbi;

const char g_index_url[128] = "https://www.dawenxue.net/50365/";
const char g_pattern[] 		= "^[ \t]*<dd><a href=\"([^\"]*)\">([^<]*)<.*";

long Dlg100ParseSelected(ST_BUTTON *ctrl,struct _Dlg100 *dlg)
{
	char url[256], reg[256];
	char output[1024];
	int i;

	dlg->idurl->GetWindowText(url, sizeof(url));
	dlg->idedtreg->GetWindowText(reg, sizeof(reg));

	regex_match_ERE(url, reg);

	memset(output, 0, sizeof(output));
	for (i = 0; i < 10; i++) {
		if (REGEX_MATCH(i)[0] != '\0') {
			//LOG("i=%d, s=%s", i, REGEX_MATCH(i));
			strncat(output, REGEX_MATCH(i), sizeof(output)-strlen(output)-1);
			strncat(output, "\r\n", sizeof(output)-strlen(output)-1);
		}
	}

	dlg->idcontent->SetWindowText(output);
	return 0;
}

long Dlg100GrabSelected(ST_BUTTON *ctrl,struct _Dlg100 *dlg)
{
	int i, r;
	FILE *fp;
	char line[1024];
	char ansiOut[1024];
	const char fname[] = "./tmp.html";

#if 1
	r = GetHttpURL(g_index_url, fname);
	if (r != 0){
		int e = GetLastError();
		ERR("error of gethttpurl = %d", e);
		return -1;
	}
#endif
	g_pbi->pages = 0;
	fp = fopen(fname, "r");
	while (1) {
		if (fgets(line, sizeof(line), fp) == NULL)
			break;

		enc_convert(line, ansiOut, CP_UTF8, CP_ACP);
		//LOG("ansiOut = %s", ansiOut);

		r = regex_match_ERE(ansiOut, g_pattern);
		if (r == 0) {
			strncpy(g_pbi->pi[g_pbi->pages].url, REGEX_MATCH(1), sizeof(g_pbi->pi[g_pbi->pages].url));
			strncpy(g_pbi->pi[g_pbi->pages].title, REGEX_MATCH(2), sizeof(g_pbi->pi[g_pbi->pages].title));

			g_pbi->pages++;
		}
	}
	fclose(fp);

	LOG("pages = %d", g_pbi->pages);

	for (i = 0; i < g_pbi->pages; i++) {
		dlg->idcbpstart->AddString(g_pbi->pi[i].title);
	}

	return 0;
}

long Dlg100Init(ST_DIALOGBOX *ctrl,struct _Dlg100 *dlg)
{
	int scrWidth, scrHeight;
    RECT rect;

	g_pbi = (book_info_t *)GC_malloc(sizeof(*g_pbi));

    scrWidth = GetSystemMetrics(SM_CXSCREEN);
    scrHeight = GetSystemMetrics(SM_CYSCREEN);
    GetWindowRect(dlg->hwnd, &rect);
#ifndef F_NO_DEBUG
	//LOG("w = %d, h = %d, rect.r,b,l,t = %d,%d,%d,%d",
	//	scrWidth, scrHeight, rect.right, rect.bottom, rect.left, rect.top);
#endif
    SetWindowPos(dlg->hwnd, HWND_TOP,
                 (scrWidth - (rect.right-rect.left)) / 2,
                 (scrHeight - (rect.bottom-rect.top)) / 2,
                 rect.right - rect.left,
                 rect.bottom - rect.top,
                 SWP_SHOWWINDOW);

	return 0;
}

BOOL WINAPI Dlg100Default(HWND hwnd,UINT msg,UINT wParam,DWORD lParam)
{
	return 0;
}

void Dlg100Destroy(HWND hwnd)
{
	EndDialog(hwnd,1);
	GC_free(g_pbi);
	return;
}
